<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2002/06/xhtml2/ http://www.w3.org/MarkUp/SCHEMA/xhtml2.xsd" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
<link href="Styles/Style02.css" rel="stylesheet" type="text/css" />
<link href="Styles/Style03.css" rel="stylesheet" type="text/css" />

<style type="text/css">body{margin:1em;background-color:transparent!important;}#sbo-rt-content *{text-indent:0pt!important;}#sbo-rt-content .bq{margin-right:1em!important;}#sbo-rt-content *{word-wrap:break-word!important;word-break:break-word!important;}#sbo-rt-content table,#sbo-rt-content pre{overflow-x:unset!important;overflow:unset!important;overflow-y:unset!important;white-space:pre-wrap!important;}</style></head>
<body><div id="sbo-rt-content"><section>

                            <header>
                    <h1 class="header-title">Thread panics</h1>
                </header>
            
            <article>
                
<p>As with anything in Rust (and pretty much any language), things can go wrong and the application will throw a panic. As with any other time a panic occurs, we can use panic! to catch the panic and then test the result to see if the thread did indeed panic. We do this using a construct such as:</p>
<pre>let handle = thread::spawn(move || { panic! ("panic occurred"); }); 
let res = handle.join(); </pre>
<p>The <kbd>join()</kbd> will return <kbd>Result&lt;T,E&gt;</kbd>, which can then be checked to see if there is an exception.</p>


            </article>

            
        </section>
    </div></body>
</html>